### ISSUE TITLE
Add directory icon

### ISSUE THREAD

**Issue by petobens** [coreyja/devicon-lookup#6]
Hi! This is awesome! Thanks for writing it up.

I found one minor thing though which I was wondering if you could change: add custom icon for directories. In the following image you can see `fzf` (actually `fd`) running for directories (top pane) and files (bottom pane) with `lsd --tree` and `bat` previews respectability. It would be really nice if you could change the directory icon to the one / similar one show by the tree preview:

![Screenshot_2019-03-12_17:50:19](https://user-images.githubusercontent.com/2583971/54235346-cc7b0e80-44ef-11e9-8c4f-9326368bb580.png)

**Comment by petobens** [comment]
In other words I would expect the following command in my home dir to return directory icons:
```
fd --type d | devicon-lookup | fzf
```
but instead I get:
![image](https://user-images.githubusercontent.com/2583971/54482694-71feec80-4826-11e9-8c22-2cce5b6ab852.png)

**Comment by coreyja** [comment]
Hey @petobens! Thanks for the kind words! Sorry for taking a bit to get back to you!

This is definitely a feature I would like to add to this project. And I think it should make for a quick feature. I can't promise when I will get to it, but I can promise I would gladly review a pull request 😃! But it is on the list of things I would like to implement eventually

**Comment by petobens** [comment]
Awesome. Thanks!

**Comment by coreyja** [comment]
I've been thinking about this a bit and one issue is that to implement this, this projects scope would have to expand a bit, as it would have to access the filesystem. Right now it solely operates on the stdin, parsing each line as a path and extracting the extension. One nice property of this, is that this utility currently operates the same no matter the directory.

It also feels like a separation of concerns issue, I would _like_ to offload the work of querying the filesystem to another tool, in this case maybe `fd`. Unfortunately I couldn't find an easy way to determine if the output was a directory simply from the output that was given by `fd`, but I haven't dived very deep into `fd` options.

I still think this is a useful addition, since this is a very common use-case, however I want to be thoughtful about how it gets added to this utility!

**Comment by petobens** [comment]
I understand your concerns but I still hope this feature finds its way into the application since, as you've said, it's a very common use case.

**Comment by coreyja** [comment]
I've come around on this issue recently! I would definitely review PRs that add this functionality, especially ones that do it behind a CLI flag!

Not sure if I will implement this in the near term or not, but it's definitely open if someone wants to take a swing at it!

**Comment by luukvbaal** [comment]
@petobens if you're still interested see https://github.com/coreyja/devicon-lookup/issues/490#issuecomment-809344524.

The script was written with `tree` output in mind which adds a `/` at the end of directories.
Not sure if thats an option for `fd`.

**Comment by coreyja** [comment]
Looking at this issue again today! It's been awhile, but I think I'll try to implement something for this here soon!

My current thoughts are that we will add a new CLI option that turns on this behavior. If the option is NOT set, we will not interact with the filesystem (just like past versions).
However if the options is provided, we will take the value (or assume the CWD if option is value-less) and use that directory as the 'base' for looking up directories.

Each line will be appended to the base path from the CLI. If this path is a directory we will use the folder icon

**Comment by petobens** [comment]
Sounds good to me :)

**Comment by coreyja** [comment]
This will be fixed in #951 when it lands! 🎉  💯
