### ISSUE TITLE
Command not working in fish...

### ISSUE THREAD

**Issue by codewizkid** [coreyja/devicon-lookup#837]
When I try and run `devicon-lookup`, or any other command with that command my terminal responds back with `fish: unknown command: devicon-lookup`. I've tried uninstalling and reinstalling devicon-lookup, nothing. Even restarting the computer doesn't fix it. Any ideas as to what might be going wrong?

Also, the same thing happens in bash, `bash: devicon-lookup: command not found`.

**Comment by coreyja** [comment]
@codewizkid 👋 Thanks for stopping by

Did you install `devicon-lookup` via cargo with `cargo install devicon-lookup`?

Have you installed other tools with `cargo` that are working? I wonder if the directory cargo installs binaries into is not on your path

For example here is my `.bash_profile` where I add the `.cargo/bin` directory to my path so I can use binaries I've installed via cargo!
https://github.com/coreyja/dotfiles/blob/master/.bash_profile#L13-L14

**Comment by codewizkid** [comment]
Oddly this didn't fix the problem for me. And yes, i did install it via cargo. And uninstalling it then reinstalling it does nothing...

**Comment by coreyja** [comment]
Can you run `$HOME/.cargo/bin/devicon-lookup` directly?

If so I think that confirms it is a PATH issue of some kind. If you copied my `.bash_profile` line exactly maybe it needs slight changes for `fish`? I'm not super familiar with fish syntax

**Comment by codewizkid** [comment]
No, nothing happens.

**Comment by backwardspy** [comment]
tested on a fresh linux install with cargo 1.71.0 and fish 3.6.1:

![image](https://github.com/coreyja/devicon-lookup/assets/289746/c15824c8-839b-4c30-b006-ae204a8543ed)

(excuse the lack of icons; this is just in tty)

i realise it's been a while since this issue was opened, but in case this is still a problem here are some ideas for debugging your environment:

- ensure that the program installed correctly and is listed under `cargo install --list`.
- ensure that `~/.cargo/bin` is on your path (`echo $PATH`), and use `fish_add_path ~/.cargo/bin` to add it if it is not.
- ensure that `~/.cargo/bin/devicon-lookup` is executable with `stat -c'%A' ~/.cargo/bin/devicon-lookup`, it should show something like `-rwxr-xr-x`.

hopefully one of these steps helps to diagnose the issue.

**Comment by coreyja** [comment]
Thanks for digging into this and the detailed comment @backwardspy!

I'm going to close this issue but if anyone is still having issues feel free to comment here.

Also if you want more 'live' support with configuring/installing `devicon-lookup` feel free to stop by my Discord and we'd be happy to debug with you!

https://discord.gg/RrXRfJNQJX
